### ISSUE TITLE
CouchDB "_attachments"

### ISSUE THREAD

**Issue by NilsNoreyson** [UnionOfRAD/lithium#73]
The current framework of Lithium seems not he be set to upload "_attachments" to CouchDB.

By using for example the FormHelper the files are not added in the CouchDB database as the, by CouchDB provided, _attachment field. Thi field could in a second step be simply loaded.

Also the by naming the field _attachment has no success since CouchDB does not allow to insert the file by this way.

The current framework makes it impossible to upload files to CouchDB.

Thanks, Nils

**Comment by davidpersson** [comment]
Building such an above mentioned abstraction turned out to be a too ambitious task. As we're not going to support GridFS in MongoDB in the future (see https://github.com/UnionOfRAD/lithium/pull/1305#issuecomment-362797237 for an explanation, same reasons apply here) it makes sense to not support it for CouchDB.
