### ISSUE TITLE
I don't like Li3 because...

### ISSUE THREAD

**Issue by jails** [UnionOfRAD/lithium#887]
Don't be shy, express yourself on things you don't like in Li3. Don't be stingy with criticisms (I personally like being abused). Makes your criticism as detailed as possible with comparisons with how it works with your favorite framework if possible.

Thanks in advance for helping us to make Li3 an even better framework.

**Comment by y-lohse** [comment]
I'm considering lithium for a project but after taking it on a test drive yesterday, I'm not really convinced. The promises and approach seems really good and I want to like it, but:

- The composer installation is broken. Something about the framework distro not being flagged as stable.
- The idea of distros is nice but there is no list available and in fact "framework" seems to be the only one, so meh…
- After a manual installation, I start the example and get a deprecation notice regarding `Mongo` and `MongoClient`. Sure, it's easy to fix, but still.
- I then noticed that the 1.0 has a beta flag and is untouched for over a year. Does not reflect well on stability or activity.
- I switched to the 1.1 branch and get internal deprecation notices (something about `String` and `Text` I think)
- I wanted to use a plugin, it did not autoload for whatever reason, and then I had to fix a bug in it (likely because it was meant for 1.0, not 1.1).

The things that work are elegant and work well, but overall and from the outset I'm not sure li3 is production grade yet.

**Comment by intel352** [comment]
@y-lohse it's definitely not. Afaik, it's never hit a final stable release (as you noted, 1.0 is still beta). Additionally, I think it's important to have a thriving community around a project, to warrant it's usage, because then there's less chance it becomes abandonware. lithium has a small dedicated community, but pretty much only in IRC or similar. It's a real shame, as when lithium *first* hit the scene, it was extremely promising. Since then, Symfony 2 has iterated multiple times, and now with Laravel available & a large community surrounding it, I don't see how lithium can be justified right now, except to do something *different*, but not for everyday use.

**Comment by y-lohse** [comment]
Thanks for the clear answer! I agree, what a shame :(. The search goes on.

**Comment by tmaiaroto** [comment]
@y-lohse @intel352 I wouldn't say Lithium isn't "stable" - it just hasn't yet labeled itself as that "1.0" we all cling to (please do keep in mind that nothing is "stable" on the web). The Lithium team is very careful about these things (there's a roadmap somewhere) to avoid "maintenance hell."

Lithium is most certainly production grade and has been used in production for many years for many projects with very good results. I assure you, it is extremely capable.

In fact, I do agree with your findings @y-lohse and they are items of discussion and are in the process of being addressed. I would suggest using the ```dev``` branch in the meantime (not 1.1).

Composer does indeed work with Lithium. Though I'm not a fan of it because it's slooooooooowwwwwww as all heck, but fortunately Lithium doesn't use it's autoloader. So I can live with it for dependency management (which is also fairly slow, but recently got faster).

If you are looking for something a little more opinionated, I could definitely see where Lithium isn't cutting it. You'll likely need to make your own set of boilerplate code that you can use for your projects that's a bit more opinionated (I use https://github.com/tmaiaroto/blackprint - fair warning, work in progress, but might give you some ideas).

Definitely good to hear more feedback!

**Comment by ericcholis** [comment]
I agree with @tmaiaroto on this one, I've been using the dev branch in production for almost a year now, and the master branch for two years before that. Both branches on a site that gets 1.5 million+ pageviews per month.

Actually, very rarely have I come across instabilities that were entirely the fault of li3. Also, in the event of a bug, the project maintainers and *small* community have fixed it rather quickly. I recommend looking through the issues and commit history to see what I'm talking about.

Lithium feels more like a solid foundation for your own project, rather than a large toolbox like Symfony. WIth that being said, Composer allows amazing flexibility to include many things that might not be included. Hell, you could even skip the built in ORM and use something like Doctrine or  Propel if you felt that Lithium's wasn't cutting it.

**Comment by SayB** [comment]
Guys ... this has not helped me to sell the idea to my employers at all!
... I've got the same answer twice: "It's not production ready yet". The
only way I can see me using Li3 now is for my own projects.

On Wed, Jul 1, 2015 at 10:15 AM, Eric Cholis <notifications@github.com>
wrote:

> I agree with @tmaiaroto <https://github.com/tmaiaroto> on this one, I've
> been using the dev branch in production for almost a year now, and the
> master branch for two years before that. Both branches on a site that gets
> 1.5 million+ pageviews per month.
>
> Actually, very rarely have I come across instabilities that were entirely
> the fault of li3. Also, in the event of a bug, the project maintainers and
> *small* community have fixed it rather quickly. I recommend looking
> through the issues and commit history to see what I'm talking about.
>
> Lithium feels more like a solid foundation for your own project, rather
> than a large toolbox like Symfony. WIth that being said, Composer allows
> amazing flexibility to include many things that might not be included.
> Hell, you could even skip the built in ORM and use something like Doctrine
> or Propel if you felt that Lithium's wasn't cutting it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnionOfRAD/lithium/issues/887#issuecomment-117690821>.
>



-- 
Regards,
Sohaib Muneer
Voice: 647-983-5903
http://blog.sohaibmuneer.com

**Comment by ericcholis** [comment]
Sorry @SayB, I'm not sure why you'd say that. I think my comments illustrated quite the opposite. I'll reiterate:

> I've been using the dev branch in production for almost a year now, and the master branch for two years before that. Both branches on a site that gets 1.5 million+ pageviews per month.

Production ready, in my opinion, is defined by the needs of the organization. In my case, when I started my project, I needed a strong PHP 5.4+ framework with baked-in support for MongoDB. What I got was a solid foundation that has been easily extensible. My needs have since shifted, but have always been met given the nature of the PHP community. Composer and it's packages filled any gaps that Lithium may have had.

As for stability and performance:

 | Last 3 months | July 2014 to June 2015
------------ | ------------ | -------------
Response Time | 295 ms | 276 ms
Uptime | 100% | 99.87%
Requests (millions) | 6.8 | 8.1

Downtime has been attributed to bad user-code, network issues, or 3rd party service issues. With the advent of PHP 7, I'm hoping to see average response times below 200 ms.

You should, of course, use this information anecdotally and compare the available frameworks to decide what is best for the needs of your project and organization.

**Comment by jails** [comment]
@intel352, in nowaday's developement, I'm not sure there's still some "bug free" libraries around. So flagging a library as "stable release" doesn't make it more stable. If you are looking at [Symfony issues](https://github.com/symfony/symfony/issues) or even [Laravel](https://github.com/laravel/framework/issues), the [li3 ones](https://github.com/UnionOfRAD/lithium/issues) are for most of them enhancements and not bugs related.

Personnaly I'm not choosing a library according to the community around. If the code base of a library doesn't make a lot of sense, no matter the community is, I'll do my best to avoid using it. Sooner or later you will need to dig into the code base of the libraries you are using to deal with some core bugs. Moreover, if the library contains some bad architecture choices it will leads you right up the wall. So you can easily waste all your profits to deal with some "unsortable" mess. I know the community size reassures people. Indeed nobody want to be alone when something bad happen. But how something bad can happen if you are understanding the libraries you are using ? I know it's quite an investment, but wasting your time posting issues and beg for help is quite time consuming too and won't make you a better coder for sure.

However it'll mostly depends on your need. If you need a lot of well defined features and are somehow compliant and not well experimented. Using a framework with a big community behind will help you to be productive in no time. But if you want to go rogue, you will waste the time you gained in the first part to finally get a messy application.

Personnaly I'm using li3 as a kind of toolbox and using some dedicated libraries for doing a job instead of following the "framework way" and get stuck as soon as I'm facing a custom use case. And since nowaday with Angular, React and all other front end tools around, li3 could be splitted up even further.

**Comment by tmaiaroto** [comment]
@SayB Ask them why.

I've been in your shoes before and I completely understand and sympathize with you. There comes a time in every programmer's life where the training wheels come off and they realize that version numbers are not an indication of "stable" or "production ready" but rather numeric devices intended to signify changes and what you're working with. That web and software and computers aren't as reliable as we'd like to believe. Unfortunately this time never comes for "employers."

**Comment by davidpersson** [comment]
@y-lohse 

> The composer installation is broken. Something about the framework distro not being flagged as stable.

Initialization of projects through composer is something we will be supporting from 1.1 onwards. We've made the availability issue in the documentation a bit clearer by rewording the notice.

![bildschirmfoto 2015-07-02 um 10 49 27](https://cloud.githubusercontent.com/assets/29702/8473223/00ecda9c-20a8-11e5-985c-17a26615c15e.png)

Installation of lithium (aka the core libraries) using composer is independent from that issue, this one already works for a long time.

> The idea of distros is nice but there is no list available and in fact "framework" seems to be the only one, so meh…

The notion of distros is also something new, we're planning for at least one more distro in the future. 

> After a manual installation, I start the example and get a deprecation notice regarding Mongo and MongoClient. Sure, it's easy to fix, but still.

This might be because you've been using the master branch distro together with the future 1.1 lithium (which is currently in flux). Or some other combination. I'd suggest to try the 1.0 branch of the distro with the latest dev branch of lithium. The lithium dev branch has the mongo fixes.

> I then noticed that the 1.0 has a beta flag and is untouched for over a year. Does not reflect well on stability or activity.

Have a look at the dev or the 1.1 branch or the issue tracker. We're continuously working on the project. However the master branch really needs a merge from dev, as dev holds lots of good stuff. We're planning for a new release once the last remaining bug on 1.0 has been fixed and some other changes we'd like to make before going 1.0 have been applied.

> I switched to the 1.1 branch and get internal deprecation notices (something about String and Text I think)

As mentioned above that branch isn't stable yet.

> I wanted to use a plugin, it did not autoload for whatever reason, and then I had to fix a bug in it (likely because it was meant for 1.0, not 1.1).

Which plugin did you try to use? Maybe I can help there.

**Comment by y-lohse** [comment]
It was [this one](https://github.com/daschl/li3_rest) but thanks, i fixed the issue :-). Our requirements are also shifting so choosing a framework is a little post-poned anyway.

I'm glad to see all the responses this generated and will definitely keep an eye out on lithium. It looks like the issue is more with communication and updating docs than with the codebase itself, which is less of a problem :p

**Comment by tmaiaroto** [comment]
I definitely agree. There is a bit of confusion and everyone is busy with things so it's hard to take the time to clarify. Have you seen this documentation repo? https://github.com/UnionOfRAD/manual  

Is there anything specific you'd want to see? Tutorials? Designed manual/docs? Any specific issues or questions you had? (aside from the ones listed above - that maybe you eventually figured out on your own, but took some time and was annoying)

**Comment by y-lohse** [comment]
I saw the manual on the website, not the actual repo but I guess the content is the same. I didn't mind the way it was designed although a search feature would be helpful.

I think the onboarding would need some love. It's exactly as you said: i eventually figured out how to resolve the issues I had, but had I not experienced them at all I would have been absolutely sold. Of course that's easier said then done :-)

**Comment by nisarg34** [comment]
Hi Lithium Team,

My client is considering LIthium for their forum related requirements.
So which all capabilities Lithium has out of the box for Forum/Community related?

Also, just wanted to check if Lithium supports (out of the box or by plugin) below functionalities:

SSO with SAML
Enterprise Search
3rd Party Java Application Integration
Unified Document Management
Document Preview
Blogs/Wikis/Polls
Content Management
Community Health 
Integrate Quartz Scheduler
Social Equity - Dynamic social capital system by measuring the contribution and participation of a user and the information value of an asset. A person can gain equity by performing certain activities within communities, such as adding contributions (e.g., wikis, blogs), rating or commenting, and viewing content.

Looking forward to hear from you

Thanks.

**Comment by davidpersson** [comment]
Thanks everybody for your suggestions and ideas! This format gathered some very helpful feedback but now got a little bit old.

**Comment by sonusen235** [comment]
Hello Everyone, Need a small help regarding upgrading li3 to php 8 version.
we are upgrading our li3 project from php 7 to php 8. Would like to know, does li3 supports php 8 ?

**Comment by nateabele** [comment]
@sonusen235 The 2.0 branch supports PHP 8.1+.
